# Generated by Django 3.2.5 on 2021-07-21 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=20)),
                ('cedula_identidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField(unique=True)),
                ('detalles_de_habitacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('ELIMINADO', 'ELIMINADO')], max_length=9)),
                ('estadia', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('metodo_de_pago', models.CharField(choices=[('CONTADO', 'CONTADO'), ('TRANSACCION', 'TRANSACCION'), ('DEBITO', 'DEBITO')], max_length=14)),
                ('monto', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hotel.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hotel.habitacion')),
            ],
        ),
    ]
