# Generated by Django 3.2.5 on 2021-07-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0005_alter_habitacion_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hotel.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hotel.habitacion'),
        ),
    ]
